name: Build Release

on: 
  workflow_dispatch:

env:
  DEPOT_DOWNLOADER_VERSION: 2.7.3 
  SL_REFERENCES: "${{ github.workspace }}/References/SCPSL_Data/Managed"
  UNITY_REFERENCES: "${{ github.workspace }}/References/SCPSL_Data/Managed"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      releasePath: "${{ github.workspace }}/main/XProxy.Shared"
    steps:
    - name: Checkout main repository.
      uses: actions/checkout@v4
      with:
        path: main
    - name: Download depot downloader
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path ${{ github.workspace }}/DepotDownloader
        Invoke-WebRequest -Uri "https://github.com/SteamRE/DepotDownloader/releases/download/DepotDownloader_${{ env.DEPOT_DOWNLOADER_VERSION }}/DepotDownloader-linux-x64.zip" -OutFile "${{ github.workspace }}/depotdownloader.zip"
        Expand-Archive -Path ${{ github.workspace }}\depotdownloader.zip -PassThru -DestinationPath ${{ github.workspace }}/DepotDownloader
        New-Item -ItemType Directory -Force -Path ${{ github.workspace }}/References
    - name: Download SCPSL Refs
      run: |
        chmod 777 ${{ github.workspace }}/DepotDownloader/DepotDownloader
        chmod 777 ${{ github.workspace }}/References
        ${{ github.workspace }}/DepotDownloader/DepotDownloader -app 996560 -os windows -dir "${{ github.workspace }}/References"
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Publish Linux x64
      run: dotnet publish ${{ github.workspace }}/main/XProxy/XProxy.csproj --configuration Release --self-contained false -p:PublishSingleFile=true --runtime linux-x64
    - name: Publish Windows x64
      run: dotnet publish ${{ github.workspace }}/main/XProxy/XProxy.csproj --configuration Release --self-contained false -p:PublishSingleFile=true --runtime win-x64
    - name: Publish Core Windows x64
      run: dotnet publish ${{ github.workspace }}/main/XProxy.Core/XProxy.Core.csproj --configuration Release --self-contained --runtime linux-x64
    - name: Build release
      id: build-release
      uses: ./XProxy.BuildRelease

    - name: Create Tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        tag_prefix: ""
        custom_tag: "${{ env.XPROXY_VERSION }}"
    - name: Make Release
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
      with:
        files: |
          ${{ github.workspace }}/main/XProxy/bin/Release/net7.0/linux-x64/publish/XProxy
          ${{ github.workspace }}/main/XProxy/bin/Release/net7.0/win-x64/publish/XProxy.exe
          ${{ github.workspace }}/main/XProxy.Core/bin/Release/net7/win-x64/publish/XProxy.Core.dll
          ${{ github.workspace }}/main/dependencies.zip
          ${{ github.workspace }}/main/releaseinfo.json
        tag_name: ${{ env.XPROXY_VERSION }}
